---
- hosts: localhost
  become: yes
  vars:
    provider_namespace: provider_ns
  vars_files:
    - subnet_vars.yml

  tasks:
          - name: Dump the configurations into json file 
            copy:
                    content: "{{ item | to_nice_json }}"
                    dest: "/etc/tenants/{{ item.value.vpc_name }}/{{ item.value.subnet_name }}.json" 
                    owner: ece792
                    group: ece792
                    mode: 0775
            with_dict: "{{ subnets }}"
