---
- hosts: localhost
  gather_facts: no
  become: yes
  vars:
          packages:
                  - docker
          docker_image: dns_centos
          docker_filepath: /home/ece792/project/DNS-as-a-Service-VPC/containerproject/dnsconf

  vars_files:
          - L3dns_vars.yml
  tasks:
          - name: Dump the configurations of DNS VM into json file
            copy:
                    content: "{{ item | to_nice_json }}"
                    dest: "/etc/tenants/{{ item.value.vpc_name }}/{{ item.key }}_L3DNS.json"
                    owner: ece792
                    group: ece792
                    mode: 0775
            with_dict: "{{ guests }}"
