---

- hosts: localhost
  gather_facts: no
  ignore_errors: yes
  become: yes
  vars:
          packages:
                  - python-libvirt
                  - python-lxml
          vm_disk_location: /var/lib/libvirt/images
          os_image_location: /home/ece792/images/dnstenantvm.img
          provider_namespace: provider_ns
  
  vars_files:
          - DNS_VM_vars2.yml
  tasks:
          - name: Dump the configurations of DNS VM into json file
            copy:
                    content: "{{ item | to_nice_json }}"
                    dest: "/etc/tenants/{{ item.key }}/{{ item.key }}-L2DNS1.json"
                    owner: ece792
                    group: ece792
                    mode: 0775
            with_dict: "{{ dns }}"

          - name: Dumping additional configurations
            copy:
                    content: "{{ item | to_nice_json }}"
                    dest: "/etc/tenants/{{ item.key }}/{{ item.key }}-L2DNS1.json"
                    owner: ece792
                    group: ece792
                    mode: 0775
            with_dict: "{{ dns }}"
