---
- hosts: localhost
  gather_facts: no
  become: yes
  vars:
          packages:
                  - docker
          docker_image: dns_centos
          docker_filepath: /home/ece792/project/DNS-as-a-Service-VPC/containerproject/dnsconf 
          dns_containers:
                  provider:
                          dns_name: L1dns
                          publish_port: 99

  tasks:
          - debug:
                  msg: "{{ dns_containers }}"
          - name: Install packages
            apt:
                    name: "{{packages}}"

          - name: Create docker images if it does not exist
            docker_image:
                    path: "{{ docker_filepath }}"
                    name: "{{ docker_image }}"
                    state: present

          - name: Create shared volume in HV
            file:
                    path: "/srv/docker/{{dns_containers[item].dns_name}}"
                    state: directory
                    mode: 0777
            with_items: "{{ dns_containers | list }}"
            
          - name: Create and start container for dns
            docker_container:
                    name: "{{ dns_containers[item].dns_name }}"
                    image: "{{ docker_image}}"
                    state: started
                    privileged: yes
                    interactive: yes
                    tty: yes
                    detach: yes
                    dns_servers:
                            - "127.0.0.1"
                    volumes:
                            - "/srv/docker/{{dns_containers[item].dns_name}}:/named"
                    published_ports:
                            - "{{dns_containers[item].publish_port}}:{{dns_containers[item].publish_port}}/udp"
            with_items: "{{ dns_containers | list }}" 

          - name: Start the named service
            command: docker exec -itd {{dns_containers[item].dns_name}} /usr/sbin/named -4 -u named -c /named/etc/named.conf
            with_items: "{{ dns_containers | list }}"
