---
- hosts: localhost
  gather_facts: no
  become: yes
  vars:
          packages:
                  - docker
          docker_image: dns_centos
          docker_filepath: /home/ece792/project/DNS-as-a-Service-VPC/containerproject/dnsconf 

  vars_files:
          - L3dns_vars.yml

  tasks:
          - debug:
                  msg: "{{ item.key }}"
            with_dict: "{{ guests }}"
          - name: Install packages
            apt:
                    name: "{{packages}}"

          - name: Create docker images if it does not exist
            docker_image:
                    path: "{{ docker_filepath }}"
                    name: "{{ docker_image }}"
                    state: present

          - name: Create shared volume in HV
            file:
                    path: "/srv/docker/{{item.key}}_L3DNS"
                    state: directory
                    mode: 0777
            with_dict: "{{ guests }}"

            
          - name: Create and start container for dns
            docker_container:
                    name: "{{ item.key }}_L3DNS"
                    image: "{{ docker_image}}"
                    state: started
                    privileged: yes
                    interactive: yes
                    tty: yes
                    detach: yes
                    dns_servers:
                            - "172.17.0.6"
                    volumes:
                            - "/srv/docker/{{item.key}}_L3DNS:/named"
                    published_ports:
                            - "{{item.value.publish_port}}:{{item.value.publish_port}}/udp"
            with_dict: "{{ guests }}" 

          - name: Start the named service
            command: docker exec -itd {{ item.key }}_L3DNS /usr/sbin/named -4 -u named -c /named/etc/named.conf
            with_dict: "{{ guests }}"

          # Create veth pair for bridge and container
          - name: Create veth pair for bridge and container
            command: "ip link add {{item.key}}vif1 type veth peer name {{item.key}}vif2"
            ignore_errors: true
            with_dict: "{{ guests }}"

          # Attach brvif2 to bridge
          - name: Attach vif2 to bridge
            command: "brctl addif {{item.value.subnet_name}} {{item.key}}vif2"
            become: yes
            ignore_errors: true
            with_dict: "{{ guests }}"

          # Make the brvif2 up
          - name: Make the vif2 up
            command: "ifconfig {{item.key}}vif2 up"
            become: yes
            with_dict: "{{ guests }}"

          # Fetch container process ID
          - name: Fetch container process ID
            shell: ip link set {{ item.key }}vif1 netns $(sudo docker inspect -f {%raw%}'{{.State.Pid}}'{%endraw%} "{{ item.key }}_L3DNS")
            #command: "docker inspect --format {%raw%}'{{.State.Pid}}'{%endraw%} {{item.key}}"
            #register: container_pid
            with_dict: "{{ guests }}"


          # Assign ip to LC1 container interface
          - name: Run dhclient
            command: docker exec --privileged "{{ item.key }}_L3DNS" dhclient {{ item.key }}vif1
            become: yes
            ignore_errors: true
            with_dict: "{{ guests }}"

          # Write to database or run this script seperately from shell
          # - name: Writing this newly created Subnet to DB
          #  include_tasks: write_dnscontl3_db.yml
          #  become: yes
