---
- hosts: localhost
  gather_facts: no
  ignore_errors: yes
  vars:
    packages:
       - python-libvirt
       - python-lxml
    vm_disk_location: /var/lib/libvirt/images
    os_image_location: /home/ece792/images/tenantvm.img
    root_pass: root
  vars_files:
       - ten_cont_vars.yml
  
  tasks:
          - name: Dump the configurations of VM into json file.
            copy:
                    content: "{{ item | to_nice_json }}"
                    dest: "/etc/tenants/{{ item.value.vpc_name }}/{{ item.key }}.json"
                    owner: ece792
                    group: ece792
                    mode: 0775
            with_dict: "{{ guests }}"
